FROM node:23.11.0-alpine AS builder 

WORKDIR /app
COPY ["package.json", "package-lock.json", "./"]
RUN npm install --unsafe-perm
COPY . .
RUN chmod +x node_modules/.bin/*
RUN npm run build


FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80